/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DB.DBLogin;
import java.sql.ResultSet;
import main.User;

/**
 *
 * @author Faroos
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
                    txtError.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uType = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtError = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(49, 49, 49));
        jPanel1.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(502, 21, 12, 472);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("On-Table Ordering System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(73, 36, 387, 34);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(723, 43, 69, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(618, 114, 72, 17);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(618, 192, 53, 17);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(618, 262, 69, 17);

        uType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Chef", "Cashier" }));
        uType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uTypeActionPerformed(evt);
            }
        });
        jPanel1.add(uType);
        uType.setBounds(620, 140, 290, 30);

        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtUser);
        txtUser.setBounds(618, 215, 290, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Designed & Developed by");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(164, 440, 161, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mohamed Faroos");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(192, 462, 107, 16);

        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPass);
        txtPass.setBounds(618, 285, 290, 30);

        txtError.setBackground(new java.awt.Color(255, 255, 255));
        txtError.setForeground(new java.awt.Color(255, 255, 102));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("Error Message");
        jPanel1.add(txtError);
        txtError.setBounds(620, 340, 290, 28);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Logo.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 150, 370, 210);

        btnLogin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 204, 102));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("Login");
        btnLogin.setToolTipText("");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(720, 380, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
                String userId=txtUser.getText();
                String userPass=txtPass.getText();
                int type=uType.getSelectedIndex();

        if(userId.isEmpty())
        {
            txtError.setVisible(true);
            txtError.setText("Please Enter User ID");
        }else if(userPass.isEmpty())
        {
            txtError.setVisible(true);
            txtError.setText("Please Enter User Password");
        }else {

            try
            {
               User user=new User();
               user.setUid(userId);
               user.setPassword(userPass);
               user.setUserType(type);
               
               DBLogin dbl=new  DBLogin();
               User us=dbl.login(user);
               String id=us.getUid();
               String password=us.getPassword();
               int userType=us.getUserType();
               String username=us.getUsername();
               
               String info[]=new String[2];  //creates an array to store  variable values. You can increase the size when needed
               info[0]=id;
               info[1]=username;
               
               
               
               if(userId.equalsIgnoreCase(id) && userPass.equalsIgnoreCase(password))
               {
                   if(userType==0)
                   {
                       Admin ad=new Admin();
                       ad.setVisible(true);
                       this.setVisible(false);
                       
                   }else if(userType==1)
                   {
                       Chef cf=new Chef();
                       cf.main(info);
                       cf.setVisible(true);
                       this.setVisible(false);
                   }else{
                       Cashier cash=new Cashier();
                       cash.main(info);
                       cash.setVisible(true);
                       this.setVisible(false);
                   }
               }else{
                    txtError.setVisible(true);
                    txtError.setText("Please Check the Your Login Details");
               }
            }catch(Exception e)
            {
                    e.printStackTrace();
                    txtError.setVisible(true);
                    txtError.setText("Please Check the Your Login Details");
            }

        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void uTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtError;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JComboBox<String> uType;
    // End of variables declaration//GEN-END:variables
}
