/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Faroos
 */
public class ManageTablet extends javax.swing.JFrame {

    /**
     * Creates new form ManageTablet
     */
    public ManageTablet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnExit = new javax.swing.JLabel();
        txtFooter = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        btnUpdateTablet = new javax.swing.JLabel();
        btnAddTablet = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabletTab = new javax.swing.JTabbedPane();
        addTablet = new javax.swing.JPanel();
        updateTablet = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(null);

        Heading.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("Manage Tablets");
        mainPanel.add(Heading);
        Heading.setBounds(30, 90, 200, 29);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainPanel.add(jSeparator1);
        jSeparator1.setBounds(260, 20, 12, 560);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 51));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        mainPanel.add(btnExit);
        btnExit.setBounds(60, 320, 140, 38);

        txtFooter.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtFooter.setForeground(new java.awt.Color(255, 255, 255));
        txtFooter.setText("Designed & Developed by Mohamed Faroos");
        mainPanel.add(txtFooter);
        txtFooter.setBounds(30, 540, 209, 21);

        txtTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setText("On-Table Ordering System");
        mainPanel.add(txtTitle);
        txtTitle.setBounds(460, 10, 251, 30);

        btnUpdateTablet.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateTablet.setForeground(new java.awt.Color(255, 255, 51));
        btnUpdateTablet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdateTablet.setText("View & Update");
        btnUpdateTablet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        btnUpdateTablet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateTablet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateTabletMouseClicked(evt);
            }
        });
        mainPanel.add(btnUpdateTablet);
        btnUpdateTablet.setBounds(60, 250, 140, 38);

        btnAddTablet.setBackground(new java.awt.Color(255, 255, 255));
        btnAddTablet.setForeground(new java.awt.Color(255, 255, 51));
        btnAddTablet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddTablet.setText("Add Tablet");
        btnAddTablet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        btnAddTablet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTablet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTabletMouseClicked(evt);
            }
        });
        mainPanel.add(btnAddTablet);
        btnAddTablet.setBounds(60, 180, 140, 38);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel2);
        jPanel2.setBounds(270, 40, 670, 50);

        addTablet.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout addTabletLayout = new javax.swing.GroupLayout(addTablet);
        addTablet.setLayout(addTabletLayout);
        addTabletLayout.setHorizontalGroup(
            addTabletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        addTabletLayout.setVerticalGroup(
            addTabletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        tabletTab.addTab("tab1", addTablet);

        updateTablet.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout updateTabletLayout = new javax.swing.GroupLayout(updateTablet);
        updateTablet.setLayout(updateTabletLayout);
        updateTabletLayout.setHorizontalGroup(
            updateTabletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        updateTabletLayout.setVerticalGroup(
            updateTabletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        tabletTab.addTab("tab2", updateTablet);

        mainPanel.add(tabletTab);
        tabletTab.setBounds(290, 41, 610, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked

        this.setVisible(false);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnUpdateTabletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateTabletMouseClicked
        tabletTab.setSelectedIndex(1);
        
    }//GEN-LAST:event_btnUpdateTabletMouseClicked

    private void btnAddTabletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTabletMouseClicked
        tabletTab.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddTabletMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTablet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTablet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JPanel addTablet;
    private javax.swing.JLabel btnAddTablet;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnUpdateTablet;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane tabletTab;
    private javax.swing.JLabel txtFooter;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JPanel updateTablet;
    // End of variables declaration//GEN-END:variables
}
