/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DB.DBBill;
import DB.DBOrderProduct;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.Bill;
import main.Order;
import main.OrderProduct;

/**
 *
 * @author Faroos
 */
public class PreviousBill extends javax.swing.JFrame {

    /**
     * Creates new form PreviousBill
     */
    public PreviousBill() {
        initComponents();
        txtError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrderProducts = new javax.swing.JTable();
        txtInvoiceNo = new javax.swing.JTextField();
        txtBalance = new javax.swing.JLabel();
        txtTitle1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtCashier = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtnetTotal = new javax.swing.JLabel();
        txtsCharge = new javax.swing.JLabel();
        txtPaidAmount = new javax.swing.JLabel();
        txtTableid = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        tblOrderProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Quantity", "Order Type", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblOrderProducts);
        if (tblOrderProducts.getColumnModel().getColumnCount() > 0) {
            tblOrderProducts.getColumnModel().getColumn(0).setMinWidth(210);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(300, 160, 450, 340);

        txtInvoiceNo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtInvoiceNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtInvoiceNo);
        txtInvoiceNo.setBounds(220, 70, 200, 30);

        txtBalance.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(255, 255, 255));
        txtBalance.setText("Balance : ");
        jPanel1.add(txtBalance);
        txtBalance.setBounds(30, 280, 260, 30);

        txtTitle1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtTitle1.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle1.setText("Check Previous Invoice");
        jPanel1.add(txtTitle1);
        txtTitle1.setBounds(250, 0, 220, 30);

        txtTotal.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setText("Ordered Items");
        jPanel1.add(txtTotal);
        txtTotal.setBounds(480, 130, 110, 30);

        txtCashier.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtCashier.setForeground(new java.awt.Color(255, 255, 255));
        txtCashier.setText("Cashier : ");
        jPanel1.add(txtCashier);
        txtCashier.setBounds(30, 380, 260, 30);

        txtDate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("Date : ");
        jPanel1.add(txtDate);
        txtDate.setBounds(30, 430, 260, 30);

        txtnetTotal.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtnetTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtnetTotal.setText("Net Total : ");
        jPanel1.add(txtnetTotal);
        txtnetTotal.setBounds(30, 130, 260, 30);

        txtsCharge.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtsCharge.setForeground(new java.awt.Color(255, 255, 255));
        txtsCharge.setText("Service Charge : ");
        jPanel1.add(txtsCharge);
        txtsCharge.setBounds(30, 180, 260, 30);

        txtPaidAmount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtPaidAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtPaidAmount.setText("Paid Amount : ");
        jPanel1.add(txtPaidAmount);
        txtPaidAmount.setBounds(30, 230, 260, 30);

        txtTableid.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtTableid.setForeground(new java.awt.Color(255, 255, 255));
        txtTableid.setText("Table ID : ");
        jPanel1.add(txtTableid);
        txtTableid.setBounds(30, 330, 260, 30);

        btnSearch.setForeground(new java.awt.Color(102, 204, 255));
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(420, 70, 60, 28);

        btnSearch1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 51, 51));
        btnSearch1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch1.setText("Exit");
        btnSearch1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch1MouseClicked(evt);
            }
        });
        jPanel1.add(btnSearch1);
        btnSearch1.setBounds(110, 480, 90, 30);

        txtError.setForeground(new java.awt.Color(255, 255, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("jLabel8");
        jPanel1.add(txtError);
        txtError.setBounds(190, 100, 270, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Invoice No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 50, 110, 16);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 130, 450, 370);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 750, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnSearch1MouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        if(txtInvoiceNo.getText().isEmpty())
        {
             txtError.setVisible(true);
             txtError.setText("Error : Please Enter Invoice No");
        }else{
            
            try {
                DBBill dbb=new DBBill();
                Bill bil=dbb.getBill(txtInvoiceNo.getText());
                
                if(bil!=null)
                {
                    txtError.setVisible(false);
                    double balance=(double) (bil.getPaidAmount()-bil.getNetTotal());
                    txtnetTotal.setText("Net Total : Rs."+bil.getNetTotal());
                    txtsCharge.setText("Service Charge : Rs."+bil.getServiceCharge());
                    txtPaidAmount.setText("Paid Amount : Rs."+bil.getPaidAmount());
                    txtTableid.setText("Table : "+bil.getTid().toUpperCase());
                    txtCashier.setText("Cashier : "+bil.getUsername().toUpperCase());
                    txtDate.setText("Date : "+bil.getBillDate());
                    txtBalance.setText("Balance : Rs"+ balance);
                    getItems(bil.getOrderId());
                
                }else{
                    txtError.setVisible(true);
                     txtError.setText("Error : Invoice No doesn't Exist");
                     
                     txtnetTotal.setText("Net Total : ");
                    txtsCharge.setText("Service Charge : ");
                    txtPaidAmount.setText("Paid Amount :");
                    txtTableid.setText("Table : ");
                    txtCashier.setText("Cashier : ");
                    txtDate.setText("Date : ");
                    txtBalance.setText("Balance : ");
                    
                    DefaultTableModel model=(DefaultTableModel)tblOrderProducts.getModel();
                    model.setRowCount(0);
                    
                }
                
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    public void getItems(String ID)
    {
        
            Order or=new Order();
            or.setOrderId(ID);
            
            DBOrderProduct dbu=new DBOrderProduct();
        
        
            List<OrderProduct> al= dbu.getOrderedItems(or);
        
            DefaultTableModel model=(DefaultTableModel)tblOrderProducts.getModel();
            model.setRowCount(0);
            Object[] row=new Object[4];
            
            for(int i=0;i<al.size();i++)
                {
                    double total=al.get(i).getQuantity()*al.get(i).getPrice();
                    

                    row[0]=al.get(i).getName();
                    row[1]=al.get(i).getQuantity();
                    int type=al.get(i).getType();
                    
                    if(type==0)
                    {
                      row[2]="Dine In";  
                    }else{
                        row[2]="Take Away";
                    }
                    
                    row[3]="Rs."+al.get(i).getQuantity()*al.get(i).getPrice();
                    
                    
                    
                    model.addRow(row);
                }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviousBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviousBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviousBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviousBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnSearch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblOrderProducts;
    private javax.swing.JLabel txtBalance;
    private javax.swing.JLabel txtCashier;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JLabel txtPaidAmount;
    private javax.swing.JLabel txtTableid;
    private javax.swing.JLabel txtTitle1;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtnetTotal;
    private javax.swing.JLabel txtsCharge;
    // End of variables declaration//GEN-END:variables
}
