/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Faroos
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        txtLoading.setVisible(false);
        txtError.setVisible(false);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLoading = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTitle1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        txtsdate = new com.toedter.calendar.JDateChooser();
        txtedate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtLoading.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtLoading.setText("Loading ....");
        jPanel1.add(txtLoading);
        txtLoading.setBounds(470, 230, 120, 40);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        txtTitle1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtTitle1.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle1.setText("Sales and Income Report");
        jPanel2.add(txtTitle1);
        txtTitle1.setBounds(400, 0, 260, 30);

        btnView.setText("View ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel2.add(btnView);
        btnView.setBounds(790, 55, 97, 35);

        txtsdate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(txtsdate);
        txtsdate.setBounds(330, 60, 190, 26);

        txtedate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(txtedate);
        txtedate.setBounds(580, 60, 190, 26);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("End Date");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(630, 40, 80, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(540, 60, 20, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Start Date");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(380, 40, 80, 20);

        txtError.setForeground(new java.awt.Color(255, 255, 102));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("jLabel4");
        jPanel2.add(txtError);
        txtError.setBounds(330, 100, 440, 20);

        btnExit.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 51, 51));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel2.add(btnExit);
        btnExit.setBounds(10, 10, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        try{
         
        if(txtsdate.getDate() == null)
        {
            txtError.setVisible(true);
            txtError.setText("Please Select Start Date");
        }else if(txtedate.getDate() == null)
        {
            txtError.setVisible(true);
            txtError.setText("Please Select End Date");
        }else{
            
            txtError.setVisible(true);
            txtError.setText("Loading......");
                jPanel1.removeAll();

                   SimpleDateFormat  df=new SimpleDateFormat("yyyy-MM-dd");
                   Date date1=txtsdate.getDate();
                   String sdate =df.format(date1);
                   Date date2=txtedate.getDate();
                   String edate = df.format(date2);


               Class.forName("com.mysql.jdbc.Driver");
               Connection    con = DriverManager.getConnection("jdbc:mysql://localhost/OTOS", "root", "");
               InputStream in = getClass().getResourceAsStream("/Reports/sales.jrxml");
               JasperDesign jd=JRXmlLoader.load(in);
               String Sql="SELECT id,oid,pid,pname,sum(quantity) as quantity,sum(price) as price,order_date,type"
                       + " FROM OrderedProduct"
                       + " where order_date >= date('"+sdate+"') AND order_date <= date('"+edate+"') "
                       + "group by pname";
               
               HashMap map = new HashMap();
               map.put("sdate", sdate);
               map.put("edate", edate);
               
               JRDesignQuery jrq=new JRDesignQuery();
               jrq.setText(Sql);
               jd.setQuery(jrq);
               JasperReport jrep=JasperCompileManager.compileReport(jd);
               JasperPrint print=JasperFillManager.fillReport(jrep, map, con) ;
               con.close();
               //JasperViewer.viewReport(print);

               JasperViewer viewer =new JasperViewer(print, true);
               viewer.setZoomRatio(CENTER_ALIGNMENT);
               Container cont=viewer.getContentPane();
               txtLoading.setVisible(false);
               jPanel1.setLayout(new BorderLayout());
               jPanel1.repaint();
               jPanel1.add(cont);
               jPanel1.revalidate();
               
               txtError.setVisible(false);
        }
        }catch(ClassNotFoundException | SQLException | JRException e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtError;
    private javax.swing.JLabel txtLoading;
    private javax.swing.JLabel txtTitle1;
    private com.toedter.calendar.JDateChooser txtedate;
    private com.toedter.calendar.JDateChooser txtsdate;
    // End of variables declaration//GEN-END:variables
}
