/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DB.DBFood;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.Food;

/**
 *
 * @author Faroos
 */
public class UpdateProduct extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
        
        txtError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle1 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrderProducts = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        txtTitle1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtTitle1.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle1.setText("Update Product Quantity");
        jPanel1.add(txtTitle1);
        txtTitle1.setBounds(220, 10, 229, 30);

        btnSearch1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 51, 51));
        btnSearch1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch1.setText("Exit");
        btnSearch1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch1MouseClicked(evt);
            }
        });
        jPanel1.add(btnSearch1);
        btnSearch1.setBounds(20, 10, 70, 30);

        txtsearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsearch.setText("Search");
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsearchKeyTyped(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(210, 60, 220, 30);

        tblOrderProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product ID", "Item Name", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(tblOrderProducts);
        if (tblOrderProducts.getColumnModel().getColumnCount() > 0) {
            tblOrderProducts.getColumnModel().getColumn(0).setMinWidth(60);
            tblOrderProducts.getColumnModel().getColumn(1).setMinWidth(250);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(80, 100, 500, 200);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Quantiry :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 330, 130, 19);

        txtqty.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtqty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtqty);
        txtqty.setBounds(320, 320, 80, 40);

        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 410, 90, 40);

        txtError.setForeground(new java.awt.Color(255, 255, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("jLabel3");
        jPanel1.add(txtError);
        txtError.setBounds(160, 370, 310, 16);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 204)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 630, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusGained
        txtsearch.setText("");
    }//GEN-LAST:event_txtsearchFocusGained

    private void btnSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnSearch1MouseClicked

    private void txtsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyTyped
            
            DBFood dbu=new DBFood();
            List<Food> al= dbu.getSearchedProducts(txtsearch.getText());
        
            DefaultTableModel model=(DefaultTableModel)tblOrderProducts.getModel();
            model.setRowCount(0);
            Object[] row=new Object[5];
            
            for(int i=0;i<al.size();i++)
                {
                    row[0]=al.get(i).getPid();
                    row[1]=al.get(i).getPname();
                    row[2]=al.get(i).getQuantity();
                                        
                    model.addRow(row);
                } 
    }//GEN-LAST:event_txtsearchKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            if(String.valueOf(tblOrderProducts.getSelectedRow()).equals("-1"))
            {
                txtError.setVisible(true);
                txtError.setText("Error : Plese Search & Select an Item");
            }else
             if(txtqty.getText().isEmpty())
            {
                txtError.setVisible(true);
                txtError.setText("Error : Please Enter Updating Quantity");
            }else 
                 if(!txtqty.getText().matches("-?\\d+(\\.\\d+)?"))
                {
                    txtError.setVisible(true);
                    txtError.setText("Error : Enter Valid Numeric Quantity");      
                }
                else{
                     
                int row = tblOrderProducts.getSelectedRow();      
                String  ID=tblOrderProducts.getValueAt(row, 0).toString();
                
                    Food fd=new Food();
                    fd.setPid(ID);
                    fd.setQuantity(Integer.parseInt(txtqty.getText()));

                    DBFood dbc=new DBFood();
                    Boolean res=dbc.updateQuantity(fd);
                
                if(res)
                {
                    txtError.setVisible(true);
                    txtError.setText("Success : Product quantity Updated"); 
                    
                    DefaultTableModel model=(DefaultTableModel)tblOrderProducts.getModel();
                    model.setRowCount(0);
                    
                    txtqty.setText("");
                }else{
                    
                    txtError.setVisible(true);
                    txtError.setText("Error : Please Select a Product");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSearch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblOrderProducts;
    private javax.swing.JLabel txtError;
    private javax.swing.JLabel txtTitle1;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
